### ISSUE TITLE
ubuntu16.04下SDK编译出错

### ISSUE THREAD

**Issue by QingSimon** [slightech/MYNT-EYE-D-SDK#1]
![image](https://user-images.githubusercontent.com/25921862/48469298-6e803800-e829-11e8-9137-5055d345b8f8.png)
请问该怎么解决？

**Comment by harjeb** [comment]
你可以试下用源码编译的opencv3.3.1

**Comment by QingSimon** [comment]
> 你可以试下用源码编译的opencv3.3.1

似乎不起作用，编译程序还是去调用了ROS下opencv的库
