### ISSUE TITLE
External Trigger or Sync?

### ISSUE THREAD

**Issue by raabuchanan** [slightech/MYNT-EYE-D-SDK#10]
Hello!

I'm curious if the new Mynt Eye D camera has the feature for depth images to be captured on a trigger from an external signal? Or is it possible to synchronize the internal clock with an external signal similar to the Intel Realsense D435 camera? If not, are there any plans to add these features in the future?

Thank you

**Comment by KalmanXiong** [comment]
We reserved the interface on hardware, but did not complete the development on firmware level. This feature will be available in the future.
