### ISSUE TITLE
Weird depth result

### ISSUE THREAD

**Issue by Sunyouh** [slightech/MYNT-EYE-D-SDK#11]
Hi,
I just got a new MYNTEYE camera and tried to get depth images, but it shows so weird depth map. tested on ubuntu 16.04 desktop PC & TX2 and got the same result.
I attached the depth image I got. I use the SDK's samples/get_image binary (tried with get_depth but nothing better). Is this something wrong with my device? or SDK? Please let me know if there is anything I could do to solve this problem. Thanks.

![mynteye_d](https://user-images.githubusercontent.com/22318563/53131899-f067b780-3522-11e9-8aed-9f7970699794.png)

**Comment by KalmanXiong** [comment]
It seems abnormal. I don't think the device had benn calibrated. You should ask for a change of device.
