### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by dheera** [slightech/MYNT-EYE-D-SDK#15]
2 issues:
0. I have cmake 3.5.1 but the install complains that I don't have >=3.0. Something is wrong with the version comparison method.

1. Can you please support CUDA 9.0, 9.1, 9.2, and 10.0? Practically nobody uses CUDA 8 anymore.
![screenshot from 2019-02-26 21-48-23](https://user-images.githubusercontent.com/1786477/53448875-5645ba80-39cd-11e9-9ead-58b45c50fe51.png)

Also, I *do* have cuda 8 in /usr/local/cuda-8.0 on my system. But /usr/local/cuda must be linked to a more recent version for everything else on my system to function.

**Comment by joinAero** [comment]
0. `Expect cmake version >= 3.0` is information, not complaint. We will change the ambiguous words.

1. SDK won't find CUDA. Maybe you need upgrade CMake (upgrade its `Modules` that check the CUDA version), or build OpenCV with `-DWITH_CUDA=OFF`.
