### ISSUE TITLE
libeSPDI missing for macOS

### ISSUE THREAD

**Issue by yarrseni** [slightech/MYNT-EYE-D-SDK#16]
Hello,

I cannot make the SDK run on macOS since there is no Mac version of libeSDPI and it has a very limited mentions number on internet overall. I could track the SDK up to the developer of the controller (http://www.etron.com/en/products/webcam_detial.php?Product_ID=10, I believe), but that would be nice to the the macOS library also included in the 3rdparty folder.

**Comment by yangruixuan** [comment]
Sorry, D series SDK can't support Mac OS yet.
