### ISSUE TITLE
Tried compiling samples using cmake, but it failed...

### ISSUE THREAD

**Issue by ljack** [slightech/MYNT-EYE-D-SDK#17]
Tried compiling samples using cmake, but it failed...

'D:\MYNTEYED\SDK\1.7.2\projects\cmake>cmake .
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- MYNTEYED_SDK_ROOT: D:\MYNTEYED\SDK\1.7.2
CMake Error at CMakeLists.txt:30 (find_package):
  Could not find a configuration file for package "mynteyed" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    D:/MYNTEYED/SDK/1.7.2/lib/cmake/mynteyed/mynteyed-config.cmake, version: 1.7.2 (64bit)

-- Configuring incomplete, errors occurred!
See also "D:/MYNTEYED/SDK/1.7.2/projects/cmake/CMakeFiles/CMakeOutput.log".

**Comment by harjeb** [comment]
@ljack  Hi, please check whether  "D:\MYNTEYED\SDK\1.7.2\bin" has added in PATH(system environment).
