### ISSUE TITLE
采集视频时跳帧

### ISSUE THREAD

**Issue by xulinkun007** [slightech/MYNT-EYE-D-SDK#2]
![21542588665_ pic](https://user-images.githubusercontent.com/30474260/48681317-a3e7a580-ebdc-11e8-8e12-cb07c2f6f275.jpg)

设置：1280x720，30fps，会有跳帧现象。
主机什么都不做（不存图像，不显示图像等），只循环接收左右图像，也不能避免跳帧。

**Comment by yangruixuan** [comment]
跳帧是主机丢帧的主动行为，处理不过来就会丢，确认是否是USB3.0接口，同时取左右目+深度会更耗资源，去掉不需要的图像，降低分辨率或者帧率会有改善
