### ISSUE TITLE
我在使用C++ SDK的时候出现了问题

### ISSUE THREAD

**Issue by shejing** [slightech/MYNT-EYE-D-SDK#20]
环境： ubuntu16.04
编译器 ：qtcreator
问题：
```
/home/jing/qtcode/mynt_camera/main.cpp:106: error: ‘class mynteyed::Image’ has no member named ‘ToMat’
         cv::Mat left = left_color.img->To(ImageFormat::COLOR_BGR)->ToMat();
                                                                    ^
```

pro文件
```
TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.cpp \
    util/cam_utils.cc \
    util/cv_painter.cc \
    util/pc_viewer.cc

INCLUDEPATH += /usr/local/include
LIBS += -L/usr/local/lib -lmynteye_depth

LIBS += -L/usr/local/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab  -lrt -lpthread -lm -ldl

HEADERS += \
    util/cam_utils.h \
    util/counter.h \
    util/cv_painter.h \
    util/optparse.h \
    util/pc_viewer.h

```

main文件是复制的getstereo.cpp
求解答。非常感谢！

**Comment by Sun-ch122** [comment]
我也遇到了这个问题,你是怎么解决的呢

**Comment by Sun-ch122** [comment]
> 我也遇到了这个问题,你是怎么解决的呢

将
/src/mynteyed/device/image.cc
`
#ifdef WITH_OPENCV
cv::Mat Image::ToMat() {
  return cv::Mat(height_, width_, get_mat_type(format_), data());
}
#endif
`
修改为:
//#ifdef WITH_OPENCV
cv::Mat Image::ToMat() {
  return cv::Mat(height_, width_, get_mat_type(format_), data());
}
//#endif
`
/include/mynteyed/device/image.h
`
#ifdef WITH_OPENCV
  cv::Mat ToMat();
#endif
`
修改为
`
//#ifdef WITH_OPENCV
  cv::Mat ToMat();
//#endif
`
重新编译

**Comment by BingXiong1995** [comment]
如果是qt就在.pro加上
DEFINES += WITH_OPENCV
DEFINES += WITH_OPENCV3

如果是visual studio就在C/C++ -> preprocessor -> preprocessor definitions中添加：
WITH_OPENCV
WITH_OPENCV3
就可以了
