### ISSUE TITLE
Windows 10 get_imu_params problem

### ISSUE THREAD

**Issue by DevAhmedYM** [slightech/MYNT-EYE-D-SDK#28]
When I run the get_imu_params on windows 10, it gives me the following error 
**"E:\Mynt Eye\MYNT-EYE-D-SDK\src\mynteyed\data\channels.cc 564:: Error reading, device went offline."**

but it continue to open the device and then gives the following error: 
**"Error: Motion intrinsics not found
This device not supported to get motion intrinsics."**

please advice.

Edit: I use Mynt Eye D with the latest SDK on master branch, and it gives me the same error with SDK 1.7.5, but on linux it works fine with sudo permission.

**Comment by harjeb** [comment]
This issue seems device disconnected，does it reproduce on latest SDK?
