### ISSUE TITLE
自动白平衡失效

### ISSUE THREAD

**Issue by xulinkun007** [slightech/MYNT-EYE-D-SDK#3]
![11542587584_ pic](https://user-images.githubusercontent.com/30474260/48681373-0a6cc380-ebdd-11e8-9b63-7aeb1a03ba23.jpg)
深度版相机的自动曝光 state_ae，设为true，仍然无法打开自动白平衡。

**Comment by yangruixuan** [comment]
这个问题原因还在查，重新刷新固件会解决，或者寄回维修，不好意思
