### ISSUE TITLE
win10 编译sdk出现问题

### ISSUE THREAD

**Issue by zranwang** [slightech/MYNT-EYE-D-SDK#32]

**Comment by zranwang** [comment]
“C:\Program Files\MYNT-EYE-D-SDK\_build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“C:\Program Files\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj”(默认目标) (3) ->
(ClCompile 目标) ->
  C:\Program Files\MYNT-EYE-D-SDK\include\mynteyed/filter/temporal_filter.h(120): error C2079: “mynteyed::TemporalFilte
r::_persistence_map”使用未定义的 class“std::array<uint8_t,256>” [C:\Program Files\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj
]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(101): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(105): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(109): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(114): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(118): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(122): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(127): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(129): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(135): error C2079: “credible_threshold”使用 未定义的
 class“std::array<uint8_t,256>” [C:\Program Files\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(146): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]
  C:\Program Files\MYNT-EYE-D-SDK\src\mynteyed\filter\temporal_filter.cpp(147): error C2109: 下标要求数组或指针类型 [C:\Program Fi
les\MYNT-EYE-D-SDK\_build\mynteye_depth.vcxproj]

    26616 个警告
    12 个错误

**Comment by harjeb** [comment]
此问题已修复，可以更新下SDK

**Comment by zranwang** [comment]
有下载链接吗？我是直接git clone https://github.com/slightech/MYNT-EYE-D-SDK.git

**Comment by harjeb** [comment]
直接git pull 就可以
