### ISSUE TITLE
Ros wrapper camera_info

### ISSUE THREAD

**Issue by molinadavid** [slightech/MYNT-EYE-D-SDK#36]
Greetings,

I am trying to integrate the camera with my current project but I'm encountering some issues, the first one I am looking into is that the camera_info message lacks the frame_id information.

Please see the follow sample of the message

```bash
header: 
  seq: 61
  stamp: 
    secs: 1562921949
    nsecs:  24430000
  frame_id: ''
height: 720
width: 1280
distortion_model: "plumb_bob"
D: [-0.2985420227050781, 0.0778045654296875, 4.1961669921875e-05, 0.000720977783203125, 0.0]
K: [703.8890991210938, 0.0, 630.2998657226562, 0.0, 704.2886352539062, 363.5127258300781, 0.0, 0.0, 1.0]
R: [0.9999951124191284, -0.001852273941040039, 0.0025098323822021484, 0.0018535852432250977, 0.9999980926513672, -0.0005115270614624023, -0.002508878707885742, 0.0005161762237548828, 0.9999966621398926]
P: [698.4000244140625, 0.0, 630.0023193359375, 0.0, 0.0, 698.4000244140625, 363.9010009765625, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```

Best regards,
David

**Comment by harjeb** [comment]
Hi, this frame id doesn't define for each topic and you can modify it in [file](https://github.com/slightech/MYNT-EYE-D-SDK/blob/master/wrappers/ros/src/mynteye_wrapper_d/launch/mynteye.launch#L155).

**Comment by molinadavid** [comment]
Hi @harjeb 

I know about the topic on the launcher, I'm sorry I should have been clearer, the problem is that when I use the launcher the topic advertised for the topics `/mynteye/depth/camera_info`, `/mynteye/left/camera_info` and  `/mynteye/right/camera_info` lack the frame_id on the message's header, however  all the other topics seem to be fine.

Thanks

**Comment by harjeb** [comment]
@m

**Comment by molinadavid** [comment]
@harjeb Thank you very much for the reply, just a question shouldn't the issue remain open until is actually fixed? other wise more people can open the same issue again assuming that it was fixed already.

**Comment by molinadavid** [comment]
Hi @harjeb  I fixed the missing frame id and created a [pull request](https://github.com/slightech/MYNT-EYE-D-SDK/pull/37), please review it and see if you find it useful
