### ISSUE TITLE
Inconsistency between StreamInfo and StreamMode

### ISSUE THREAD

**Issue by olya-gm** [slightech/MYNT-EYE-D-SDK#39]
From GetDeviceInfos(), I as one of the options I get resolution of 2560 by 960. But it doesn't seem to be possible to set it through the StreamMode which does not offer such a resolution. Is this the intended behavior?

Thanks in advance.

**Comment by harjeb** [comment]
Yes, we supply 720p instead of 960p cause 720p is more popular
