### ISSUE TITLE
获取的图像有畸变

### ISSUE THREAD

**Issue by 18660814995** [slightech/MYNT-EYE-D-SDK#4]
通过Sample获取的例程有明显畸变，尤其是RGB图，目前深度图是否有畸变暂时未发现；
后通过void | SetImageMode (const ImageMode &mode)该函数配置后依旧没有效果

**Comment by joinAero** [comment]
打开时，参数可选原图或纠正。选用 COLOR_RECTIFIED 即可。

// Color mode: raw(default), rectified
params.color_mode = ColorMode::COLOR_RECTIFIED;
