### ISSUE TITLE
What is the recommended way to obtain data(images) without any post-processing?

### ISSUE THREAD

**Issue by srkm009** [slightech/MYNT-EYE-D-SDK#43]
I used your sdk and tried to see the quality of the image at highest resolution and 30fps(in Ubuntu 16.04). Images looked a bit washed-out or post-processed. I also tried using the ROS way and still find the images of similar quality. Could you recommend the best way to receive the raw-unprocessed data from the camera?

**Comment by jiziye** [comment]
The image format of the D1000 is YUYV. The SDK can only get the processed image.

**Comment by srkm009** [comment]
Ok. Thanks for the update @jiziye. 
It would be really great if MYNT-EYE provide the user the option to select if the post processing needs to be done or not.
