### ISSUE TITLE
Error: Device not found

### ISSUE THREAD

**Issue by xiaomaicha** [slightech/MYNT-EYE-D-SDK#5]
你好，sdk编译很正常，但是在运行sample的时候却说没有找到设备，这是怎么回事呢，USB接的是3.0的。是固件的问题吗？
I/eSPDI_API: eSPDI: EtronDI_Init
Device descriptors:
  name: MYNT-EYE-D1000
  serial_number: 2038375335485017002A0056
  firmware_version: 1.0
  hardware_version: 2.0
  spec_version: 1.0
  lens_type: 0000
  imu_type: 0000
  nominal_baseline: 120

Error: Device not found

**Comment by Lamine22** [comment]
I have a simple test application (derived from samples) that works fine on an ubuntu 16.04 x86-64 with **SDKv1.7.8**  but the same application (cross compiled for a custom Linux distribution x86-64) leads to this same issue #5 : 

root@CTX18000000M:~# ./testMyntEyeD 
Pas d'arguments. mode stream uniquement
**I/eSPDI_API: eSPDI: EtronDI_Init**
Device descriptors:
  name: MYNT-EYE-D1000
  serial_number: 2038375335485017002A0041
  firmware_version: 1.0
  hardware_version: 2.0
  spec_version: 1.0
  lens_type: 0000
  imu_type: 0000
  nominal_baseline: 120
INFO : Select device

**I/eSPDI_API: eSPDI: EtronDI_Init**

**I/eSPDI_API: eSPDI: EtronDI_Init**

**Error: Device not found
Error: Select failed**
root@CTX18000000M:~# 

Kernel version for this custom yocto distribution is : # uname -a
Linux CTX18000000M **4.12.21-yocto-standard** #1 SMP PREEMPT Wed Nov 21 14:39:41 UTC 2018 x86_64 GNU/Linux 

It seems to be an error related to eSPDI API... Could you please advise ?
Lamine22

**Comment by ygambhir** [comment]
Was anyone able to figure out this issue? I'm currently getting a similar issue with running the MYNT EYE D SDK samples with my camera connected to my computer:

I/eSPDI_API: eSPDI: EtronDI_InitunameData.release = 4.4.0-43-Microsoft                                                  version 4.4.0                                                                                                                                                                                                                                   I/eSPDI_API: eSPDI: EtronDI_InitunameData.release = 4.4.0-43-Microsoft                                                  version 4.4.0                                                                                                                                                                                                                                                                                                                                                           I/eSPDI_API: eSPDI: EtronDI_InitunameData.release = 4.4.0-43-Microsoft                                                  version 4.4.0                                                                                                                                                                                                                                                                                                                                                           Error: Device not found

Any help or direction would be appreciated!
