### ISSUE TITLE
The pointcloud result of box is NOT good, how to fix ?  

### ISSUE THREAD

**Issue by zhaoyingdeveloper** [slightech/MYNT-EYE-D-SDK#51]
Hi guys, 
The following pictures are the pointcloud results from a box on table, they are the front view, top-down view and original rgb(left eye) from Rviz images respectively.  I found that the pointcloud of box surface is not a line but multiple lines from the top-down view. I have tried to fix it through adjusting light and setting IR in launch files but the result is still not good. Do u guys have any suggestions to get a better pointcloud effect through adjusting other camera parameters to fix the multiple lines problems( I want it to be one line) pointcloud result as shown in the last images ? 

1. front view:
![IMG_9083](https://user-images.githubusercontent.com/51750042/67139111-d2538200-f27e-11e9-8ed6-cd444aae9347.JPG)

2. top-down view:
![IMG_9082](https://user-images.githubusercontent.com/51750042/67139112-d5e70900-f27e-11e9-95c5-f20d8a9cdaad.JPG)

3. original rgb(ps: cropped some background in this image)
![IMG_9084](https://user-images.githubusercontent.com/51750042/67139113-d8e1f980-f27e-11e9-9ddf-a0916289d2f7.JPG)

4. mutiple lines for a box surface which should be a line from top-down view
![mul](https://user-images.githubusercontent.com/51750042/67139206-ff546480-f27f-11e9-9af1-272a7b5978c0.JPG)

**Comment by harjeb** [comment]
Please make sure firmware is latest and try re calibrate device
