### ISSUE TITLE
Multiple mynt eye d's dont work on one usbhub

### ISSUE THREAD

**Issue by lorugant123** [slightech/MYNT-EYE-D-SDK#53]
HI, I am trying to open 3 cameras using acroname usb hub and it doesn't work. It detects only two cameras in that scenario. The third one does show up in device descriptors but says "Open camera failed". Is it due to the data rate? I am using 3.0 usb hub though which should run at 5gbps. And I am running all cameras at 30fps. When I check dmesg the third myntd gets detected and the "lsusb -t" also shows 3 devices at 5000Mbps. So any help would be appreciated. Thank you!

**Comment by harjeb** [comment]
SDK not support multiple mynt eye d devices right now
