### ISSUE TITLE
Multiple cameras failing

### ISSUE THREAD

**Issue by stoneking** [slightech/MYNT-EYE-D-SDK#55]
I have two mynteye P cameras connected to the same computer
When I run the get_points2 sample program with either camera, alone, it succeeds.
Attempting to run get_points2 with the second camera while the first instance of get_points2 is still running results in the second invocation exiting with output that ends with the following:

Open device: 1, /dev/video3

>D/eSPDI_API: SetPropertyValue control=7 value=0D/eSPDI_API: SetPropertyValue control=7 >value=35D/eSPDI_API: SetPropertyValue control=7 value=1-- Auto-exposure state: enabled
>D/eSPDI_API: SetPropertyValue control=7 value=0D/eSPDI_API: SetPropertyValue control=7 >value=12D/eSPDI_API: SetPropertyValue control=7 value=1-- Auto-white balance state: enabled
>-- Framerate: 10
>D/eSPDI_API: SetPropertyValue control=7 value=2-- Color Stream: 1280x720 YUYV
>-- Depth Stream: 1280x720 YUYV
>D/eSPDI_API: SetPropertyValue control=7 value=0D/eSPDI_API: SetPropertyValue control=7 >value=3D/eSPDI_API: SetPropertyValue control=7 value=4
>-- IR intensity: 4
>D/eSPDI_API: CVideoDevice::OpenDevice 1280x720 fps=10
>start_capturing() failed .
>D/eSPDI_API: CVideoDevice::OpenDevice 1280x720 fps=10
>start_capturing() failed .
>
>Error: Open camera failed

The second invocation of get_points2 fails without affecting the first invocation, regardless of whether it is device 0 or device 1 that is opened first.

This appears to be different behavior from that reported in issue #30 
I cannot determine if this has the same cause as issue #44 

Thanks for your help.

**Comment by harjeb** [comment]
SDK not support multi device yet
