### ISSUE TITLE
make ros error!

### ISSUE THREAD

**Issue by lqql2012** [slightech/MYNT-EYE-D-SDK#59]
hello,i am trying to build the nodes for stereo ,but I get the following error:
mynteye_listener.cc:21:41: fatal error: mynteye_wrapper_d/GetParams.h: No such file or directory

**Comment by harjeb** [comment]
Make sure your SDK folder path not contains special character like Chinese, Japanese etc.

**Comment by lqql2012** [comment]
@harjeb  hello ,I am sure the folder path is full English！

**Comment by harjeb** [comment]
Hi Could you attach your build log or picture?

**Comment by lqql2012** [comment]
/home/lqql/slam/MYNT-EYE-D-SDK/wrappers/ros/src/mynteye_wrapper_d/src/mynteye_listener.cc:21:41: fatal error: mynteye_wrapper_d/GetParams.h: No such file or directory
compilation terminated.
mynteye_wrapper_d/CMakeFiles/mynteye_listener_d.dir/build.make:62: recipe for target 'mynteye_wrapper_d/CMakeFiles/mynteye_listener_d.dir/src/mynteye_listener.cc.o' failed
make[3]: *** [mynteye_wrapper_d/CMakeFiles/mynteye_listener_d.dir/src/mynteye_listener.cc.o] Error 1
make[3]: Leaving directory '/home/lqql/slam/MYNT-EYE-D-SDK/wrappers/ros/build'
CMakeFiles/Makefile2:490: recipe for target 'mynteye_wrapper_d/CMakeFiles/mynteye_listener_d.dir/all' failed
make[2]: *** [mynteye_wrapper_d/CMakeFiles/mynteye_listener_d.dir/all] Error 2
make[2]: Leaving directory '/home/lqql/slam/MYNT-EYE-D-SDK/wrappers/ros/build'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lqql/slam/MYNT-EYE-D-SDK/wrappers/ros/build'
Invoking "make -j12 -l12" failed
Makefile:121: recipe for target 'ros' failed
make: *** [ros] Error 1

**Comment by lqql2012** [comment]
Maybe the file　''GetParams.srv'' 　is not compiled into .h file?

**Comment by harjeb** [comment]
Try `make cleanall && make uninstall && make all`

**Comment by lqql2012** [comment]
@harjeb 　Still have the same error...

**Comment by harjeb** [comment]
Hi Is it the latest SDK ? we also have a installtion [video for MYNT-EYE-S-SDK](https://www.bilibili.com/video/av68237965) ，the only difference is D-SDK should `make init` before `make all`

**Comment by lqql2012** [comment]
lqql@lqql-ZHENGJIUZHE-REN9000-25ICZ:~/slam/xiaomi/MYNT-EYE-D-SDK$ make init
Make init
Init tools
Install cmd: sudo apt-get install
Install deps: build-essential curl cmake git make
All deps already exist
Init deps
Install cmd: sudo apt-get install
Install deps: libv4l-dev libjpeg-dev libgtk-3-dev libusb-dev
All deps already exist
 
Note:: Because of the problem of device permissions, you must reinsert the camera device after the command is executed and on the same computer, this operation only needs to be done once..

**Comment by lqql2012** [comment]
@harjeb  i have solve it,ti just a em version problem ,thank you very much!!

**Comment by BinuxLiu** [comment]
@lqql2012 Can you tell me how to solve it ? EM version problem ?
