### ISSUE TITLE
用opencv 接口 打不开相机， class mynteyed::Image  has no member named 'ToMat',

### ISSUE THREAD

**Issue by dqqDQ** [slightech/MYNT-EYE-D-SDK#67]

**Comment by dqqDQ** [comment]
[CMakeLists.txt](https://github.com/slightech/MYNT-EYE-D-SDK/files/4266033/CMakeLists.txt)

**Comment by IamWangYunKai** [comment]
Remove```#ifdef WITH_OPENCV``` and ```#endif``` from line 152 and line 154 in ```include/mynteyed/device/image.h``` and line 170 and line 174 in ```src/mynteyed/device/image.cc``` may work.

**Comment by dqqDQ** [comment]
> .

All right.Thank you !
