### ISSUE TITLE
raspberrypi 编译错误

### ISSUE THREAD

**Issue by PotiXIE** [slightech/MYNT-EYE-D-SDK#8]
-- Build files have been written to: /home/pi/temp/MYNT-EYE-D-SDK/_build
make[1]: Entering directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
make[2]: Entering directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
make[3]: Entering directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
make[3]: Leaving directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
make[3]: Entering directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
[  4%] Linking CXX shared library ../_output/lib/libmynteye_depth.so
/home/pi/temp/MYNT-EYE-D-SDK/3rdparty/eSPDI/linux/x64/libeSPDI.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
CMakeFiles/mynteye_depth.dir/build.make:660: recipe for target '../_output/lib/libmynteye_depth.so.1.6.0' failed
make[3]: *** [../_output/lib/libmynteye_depth.so.1.6.0] Error 1
make[3]: Leaving directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mynteye_depth.dir/all' failed
make[2]: *** [CMakeFiles/mynteye_depth.dir/all] Error 2
make[2]: Leaving directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
Makefile:60: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by KalmanXiong** [comment]
Try the latest release

**Comment by PotiXIE** [comment]
thanks you !, after updated , make all, error:

[ 86%] Building CXX object CMakeFiles/mynteye_depth.dir/src/mynteyed/data/hid/hid_linux.cc.o
[ 91%] Building CXX object CMakeFiles/mynteye_depth.dir/src/mynteyed/device/linux/color_palette_generator.cc.o
[ 95%] Building CXX object CMakeFiles/mynteye_depth.dir/src/mynteyed/device/linux/device_linux.cc.o
[100%] Linking CXX shared library ../_output/lib/libmynteye_depth.so
/home/pi/temp/MYNT-EYE-D-SDK/3rdparty/eSPDI/linux/x64/libeSPDI.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
CMakeFiles/mynteye_depth.dir/build.make:660: recipe for target '../_output/lib/libmynteye_depth.so.1.6.2' failed
make[3]: *** [../_output/lib/libmynteye_depth.so.1.6.2] Error 1
make[3]: Leaving directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mynteye_depth.dir/all' failed
make[2]: *** [CMakeFiles/mynteye_depth.dir/all] Error 2
make[2]: Leaving directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/temp/MYNT-EYE-D-SDK/_build'
Makefile:60: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by yangruixuan** [comment]
What is model of your raspberry pi?

**Comment by yangruixuan** [comment]
32bit CPU is not supported

**Comment by HTLife** [comment]
@yangruixuan I just successfully compile the source code on RaspberryPi 4 with 64bit CPU.
However, when I tried `get_image` the error message:
```
./samples/_output/bin/get_image
I/eSPDI_API: eSPDI: EtronDI_InitunameData.release = 4.19.69-v7l+
version 4.19.69
Bus error
```
How can I resolve it?
